name: Bug
description: Known defect to fix
labels: ["type:bug", "status:triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is broken?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal reproduction steps.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the system does this affect?
      multiple: true
      options:
        - hex-grid
        - camera
        - game-system
        - cell
        - unit
        - editor-ui
        - ontology
        - rules-engine
        - scripting
        - persistence
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Output of the version tag or Cargo.toml version
      placeholder: "v0.6.0"
