name: Pitch
description: Shaped proposal for the betting table — ready to be scheduled
labels: ["type:pitch"]
body:
  - type: markdown
    attributes:
      value: |
        A pitch is a shaped, risk-reduced proposal. Only pitches are considered at the betting
        table. See `docs/guides/shape-up.md` for the full Shape Up reference.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: >-
        What pain point or opportunity does this address? Why does it matter now? Include concrete
        examples of the current workaround or gap.
    validations:
      required: true
  - type: dropdown
    id: appetite
    attributes:
      label: Appetite
      description: >-
        How much time is this worth? Small Batch = 1-2 weeks. Big Batch = full cycle.
      options:
        - "Small Batch (1-2 weeks)"
        - "Big Batch (full cycle)"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: >-
        The shaped solution — rough enough to leave room for implementation decisions, solved enough
        that the builder knows the approach. Use breadboards, fat marker sketches, or written
        walkthroughs.
    validations:
      required: true
  - type: textarea
    id: rabbit-holes
    attributes:
      label: Rabbit holes
      description: >-
        Known risks and the decisions made to prevent them. What tricky spots exist and how are they
        mitigated?
  - type: textarea
    id: no-gos
    attributes:
      label: No gos
      description: >-
        Functionality deliberately excluded to fit the appetite. What are we NOT building?
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the system does this affect?
      multiple: true
      options:
        - hex-grid
        - camera
        - game-system
        - cell
        - unit
        - editor-ui
        - ontology
        - rules-engine
        - scripting
        - persistence
        - contracts
        - process
    validations:
      required: true
  - type: textarea
    id: build-checklist
    attributes:
      label: Build Checklist
      description: >-
        Numbered list of deliverable scopes for the build phase. Each item should be a concrete,
        independently completable piece of work. During the build, agents reference checklist items
        by number in progress comments and include the commit SHA when a scope is done.
      placeholder: |
        - [ ] 1. <scope name> — <brief description>
        - [ ] 2. <scope name> — <brief description>
        - [ ] 3. <scope name> — <brief description>
  - type: textarea
    id: lifecycle
    attributes:
      label: Lifecycle
      description: >-
        Tracks the pitch through the integration pipeline. Agents check items off as they complete
        each phase. The last checked item shows where to resume if work is restarted. See
        docs/guides/agent-ops.md for guard prerequisites.
      value: |
        - [ ] Branch created from integration branch *(pitch agent)*
        - [ ] Build started — kickoff comment posted *(pitch agent)*
        - [ ] All build checklist scopes complete *(pitch agent)*
        - [ ] Quality gate passed — `mise check:audit` *(pitch agent)*
        - [ ] Ready for integration — spec criteria met, deferred items captured *(pitch agent)*
        - [ ] Merged to integration branch *(cycle agent)*
        - [ ] Build reflection posted *(pitch agent)*
  - type: textarea
    id: raw-ideas
    attributes:
      label: Related raw ideas
      description: >-
        Link to GitHub Issues (raw ideas) that this pitch addresses. Use #number references.
